- name: create and attach ebs volumes
  ec2_vol:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    instance: "{{ item.instance_ids[0] }}"
    device_name: "{{ disk_name[1].name }}"
    volume_size: "{{ disk_name[1].size }}"
    region: "{{ item.item.region }}"
  register: ebscreate
  loop: "{{ vmcreate.results }}"
